baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = 'Welcome to the Gibbiverse'
theme = 'ananke'



[params]
  author = 'Scott Gibb'
  [params.contact]
    email = 'smgibb@yahoo.com'
    linkedin = 'https://www.linkedin.com/in/scott-gibb-ces/'


  description = 'A blog about tech, life, and everything in between.'
  showReadingTime = true
  mainSections = ['posts', 'page']

[caches]
  [caches.images]
    dir = ':cacheDir/images'